baseURL: https://leovct.github.io/
title: leovct.dev
theme: PaperMod
pagination:
  pagerSize: 5
googleAnalytics: G-7BWGX7L5F0

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  assets:
    favicon: favicon.ico

  # Home page
  homeInfoParams:
    title: Salut ! 👋
    image:
      url: profile.jpg
      title: Profile picture
    content: |
      - My name is Léo. I'm a french software engineer.
      - I currently work at [Polygon Labs](https://polygon.technology/), developing layer 2 solutions to help scaling Ethereum (prev: [platform engineer](https://github.com/resources/articles/software-development/what-is-platform-engineering) at [Renault Software Factory](https://twitter.com/renaultgroup) and student at [INP ENSEEIHT](https://www.enseeiht.fr/en/enseeiht.html)).
      - I'm very interested in blockchain technologies and web3 security at the moment. Other than that, I'm just a random baguette guy with a passion for crossfit, trail running, and outdoor adventures.
    social:
      align: right
      icons:
        - name: github
          url: https://github.com/leovct
        - name: twitter
          url: https://twitter.com/leoovct
        - name: linkedin
          url: https://www.linkedin.com/in/vincentleo/

  # Posts options
  showToc: true
  showReadingTime: true
  showWordCount: true
  showCodeCopyButtons: true
  cover:
    hidden: true
    hiddenInSingle: false
  editPost:
    URL: https://github.com/leovct/leovct.github.io/tree/main/content/
    Text: 📝 Suggest changes
    appendFilePath: true

  # Search options
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys:
      - title
      - permalink
      - summary
      - content

# Enable search
outputs:
  home:
    - HTML
    - JSON # is necessary

menu:
  main:
    - identifier: home
      name: home
      url: /
      weight: 1
    - identifier: articles
      name: articles
      url: /articles/
      weight: 2
    - identifier: projects
      name: projects
      url: /projects/
      weight: 3
    - identifier: search
      name: search
      url: /search/
      weight: 4
