---
name: Weekly submodules update

on:
  schedule:
    - cron: '0 5 * * 1' # Run every Monday at 6 AM (UTC+1) - Paris

env:
  PNPM_VERSION: '8.11.0'

jobs:
  submodules-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Update submodules
        run: |
          git config pull.rebase false
          pnpm run update

      - name: Check for changes
        id: check_changes
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "✅ Changes detected!"
            echo "::set-output name=changes::true"
          else

      - name: Create PR
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          branch_name="submodules-update-$(date +'%Y%m%d')"
          git checkout -b $branch_name
          git add .
          git commit -m "[🤖] chore: update submodules"
          git push origin $branch_name
          hub pull-request -m "[🤖] chore: update submodules" -b main -h $branch_name
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
