---
name: Weekly submodules update

on:
  schedule:
    - cron: '0 5 * * 1' # Run every Monday at 6 AM (UTC+1) - Paris
  workflow_dispatch: # To debug.

env:
  PNPM_VERSION: '8.11.0'

jobs:
  submodules-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Update submodules
        run: pnpm run update

      - name: Check for changes
        id: check_changes
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "✅ Changes detected!"
          else
            echo "No changes detected."
          fi

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: 'chore/update-submodules'
          commit-message: 'chore: update submodules'
          title: 'chore: update submodules'
