# This workflow runs the markdownlint linter.
# https://github.com/DavidAnson/markdownlint

---
name: Run markdownlint

on:
  push:
    branches:
      - "*"
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Create an empty package-lock.json file
      run: touch package-lock.json

    - name: Setup node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    
    - name: Install markdownlint-cli
      run: npm install -g markdownlint-cli

    - name: Run markdownlint
      run: make lint
