name: Run linter

on:
  pull_request:
  push:
    branches: [main]

env:
  PNPM_VERSION: '9.12.2' # https://www.npmjs.com/package/pnpm

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Install dependencies
        run: pnpm install

      - name: Run linter
        run: pnpm run check
